/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as LocaisHospitalIdRouteImport } from './routes/locais.$hospitalId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const LocaisHospitalIdRoute = LocaisHospitalIdRouteImport.update({
  id: '/locais/$hospitalId',
  path: '/locais/$hospitalId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/locais/$hospitalId': typeof LocaisHospitalIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/locais/$hospitalId': typeof LocaisHospitalIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/locais/$hospitalId': typeof LocaisHospitalIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/locais/$hospitalId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/locais/$hospitalId'
  id: '__root__' | '/' | '/locais/$hospitalId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LocaisHospitalIdRoute: typeof LocaisHospitalIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locais/$hospitalId': {
      id: '/locais/$hospitalId'
      path: '/locais/$hospitalId'
      fullPath: '/locais/$hospitalId'
      preLoaderRoute: typeof LocaisHospitalIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LocaisHospitalIdRoute: LocaisHospitalIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
